spring.application.name=backend


spring.datasource.url=jdbc:postgresql://localhost:5433/cytech_entreprise
spring.datasource.username=cytech_user
spring.datasource.password=CyT3ch2025!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=la_cle_secrete_tres_longue_au_moins_256_bits_pour_securite_maximale
jwt.expiration=86400000

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.fr.springboot.backend=DEBUG
logging.level.org.springframework.security=DEBUG
