spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/cytech_entreprise
spring.datasource.username=cytech_user
spring.datasource.password=CyT3ch2025!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
